const Map<String, String> filPH = {
  "selectLang": "Pagpili ng Wika",
  "selectLangBody": "Piliin ang iyong ginustong wika",
  "saveLang": "Magtipid",
  "permissionTitle": "Magbigay ng Mga Pahintulot",
  "permissionButton": "Payagan",
  "permissionText1":
      "Magbigay ng Access sa Pag-contact upang suriin kung sino ang gumagamit ng Payso",
  "permissionText2":
      "Pag-access sa Camera upang i-scan ang mga QR code ng Camera",
  "permissionText3":
      "Magbigay ng Access sa Lokasyon makakuha ng mga pahintulot",
  "sliderTitle1": "QR at Mga Instant na Pagbabayad",
  "sliderTitle2": "Mga Bayad sa Bill",
  "sliderTitle3": "Seguridad",
  "sliderTitle4": "Mag-withdraw ng Mga Pondo",
  "sliderButton1": "Magsimula",
  "sliderButton2": "Simulan ang Pagbabayad ng Mga Pagsingil",
  "sliderButton3": "Malamig!",
  "sliderButton4": "Magisumla na tayo",
  "skipLogin": "laktawan upang mag-login",
  "registrationTitle": "Pagpaparehistro",
  "registrationBody":
      "Ipasok ang iyong mobile number upang makatanggap ng verification code",
  "phoneHint": "Ilagay ang Numero ng telepono",
  "otpButton": "Kumuha ng OTP",
  "phoneEmpty": "Mangyaring Ipasok ang wastong numero ng telepono",
  "verifyNumberTitle": "Patunayan ang iyong numero",
  "verifyNumberBody": "Magpasok ng isang numero ng 6 na digit na ipinadala sa",
  "verifyResendCode": "Ipadala muli ang Code",
  "otpInvalid": "Mangyaring Ipasok ang Valid OTP",
  "backButton": "Bumalik",
  "incorrectTitle": "Maling OTP",
  "incorrectOTPContent": "Ang OTP na iyong ipinasok ay mali",
  "incorrectButton": "Sige",
  "otpVerifyButton": "Patunayan",
  "mobileVerifiedDesc": "Ang iyong numero ng mobile ay matagumpay na na-verify",
  "completeProfileTitle": "Kumpletuhin ang Profile",
  "completeProfileName": "Ipasok ang Iyong Pangalan",
  "incorretProfileName": "Dapat may bisa ang haba ng pangalan",
  "completeProfileEmail": "Ipasok ang Iyong Email",
  "incorrectProfileEmail": "Magpasok ng wastong email",
  "completeProfileReferral": "Sanggunian Code",
  "completeProfileNext": "Susunod",
  "setPasscodeTitle": "Itakda ang Mobile Passcode",
  "setPasscodeBody":
      "Magpasok ng isang 4 digit na passcode upang ma-secure ang iyong account",
  "PasscodeDigitsOnly": "Ipasok ang Mga Digit Lamang",
  "incorrectSetPasscode": "Mangyaring Ipasok ang wastong passcode",
  "setPasscodeButton": "Kumpirmahin ang Passcode",
  "confirmPasscodeTitle": "Kumpirmahin ang Mobile Passcode",
  "confirmPasscodeBody":
      "Mangyaring Ipasok muli ang iyong 4 na digit na passcode",
  "incorrectConfirmPasscode":
      "Hindi tumutugma ang Passcode, Mangyaring Suriin !!",
  "confirmPasscodeButton": "Itakda ang Passcode",
  "passcodeVerifedDesc": "Ang iyong passcode ay matagumpay na naitakda",
  "secureTitle": "I-secure ang iyong Payso",
  "secureControllerBody": "I-scan ang iyong daliri upang patunayan",
  "SecureButton": "Suriin sa Biometric"
};
